EVALUATE
{
    COUNTROWS (
        GENERATEALL (
            ALL ( Customer ),
            SELECTCOLUMNS (
                OFFSET (
                    -1,
                    ALL ( Customer ),
                    ORDERBY ( Customer[CustomerKey] ),
                    MATCHBY ( Customer[CustomerKey] )
                ),
                "Previous Name", Customer[Name]
            )
        )
    )
}
