EVALUATE
SUMMARIZECOLUMNS (
    Product[Brand],
    'Date'[Year],
    "Sales", [Sales Amount],
    "Sales First Year",
        CALCULATE (
            [Sales Amount],
            INDEX (
                1,
                ORDERBY ( 'Date'[Year] )
            )
        ),
    "Sales Last Year",
        CALCULATE (
            [Sales Amount],
            INDEX (
                -1,
                ORDERBY ( 'Date'[Year] )
            )
        )
)
